### ISSUE TITLE
命令行执行出错

### ISSUE THREAD

**Issue by bluesmli** [dechenx83/automation_test#1]
命令行执行出错,提示模块不存在，需要在start.py 中加
import sys
import os
curPath = os.path.abspath(os.path.dirname(__file__))
rootPath = os.path.split(curPath)[0]
sys.path.append(rootPath)

**Comment by dechenx83** [comment]
Thanks. fixed in https://github.com/dechenx83/automation_test/commit/0624e885977e7c151e3b89200f8c400bf8dbf6c9
will add setup.py script soon to make it as a package.
