### ISSUE TITLE
测试用例依赖的用例执行通过，但是测试仍然无法执行，提示依赖的用例未执行

### ISSUE THREAD

**Issue by Vodkav** [dechenx83/automation_test#5]
case1:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/54149775/112314506-118fc900-8ce4-11eb-8962-c4075c610127.png">
case2:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/54149775/112314589-25d3c600-8ce4-11eb-8894-335391a85509.png">

reporter:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/54149775/112314672-3dab4a00-8ce4-11eb-9955-11434c6b730b.png">

我认为是下面这段代码造成的：
 
<img width="695" alt="image" src="https://user-images.githubusercontent.com/54149775/112314978-9975d300-8ce4-11eb-868a-20e36430f4e5.png">

**Comment by dechenx83** [comment]
谢谢，除了这段代码漏了一个return True, 然后在处理node result更新的时候也有一些问题。修改的代码已经commit。
